cryptopus-postgres:
    image: postgres:12.10
    container_name: cryptopus-postgres
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - cryptopus-postgres:/var/lib/postgres
